### PR TITLE
Convert Docker image to be biobox compatible

### PR DESCRIPTION
**Pull request by michaelbarton**
Aaron, I'd like to make your image compatible with the rest of the images on bioboxes. I've made some changes, mainly to convert the biobox.yaml input argument file into the libs file outlined in the documentation.

After discussion with @atritt, would it be possible to license this as BSD or MIT? I believe there are certain consequences for using GPL.

### CODE REVIEW

**Comment by koadman** [comment]
looks good. we should update to the latest A5-miseq release as well, but I will push that change separately.

**Comment by koadman** [comment]
btw, I'm happy for this to all be licensed BSD. your call really since it's all derived from your Docker template for nucleotid.es

**Comment by koadman** [comment]
i just noticed you've already got it pointed to the latest release. fantastic.

**Comment by michaelbarton** [comment]
Thanks Aaron. I've included this in the next set of nucleotides evaluations. I'd recommend BSD for the docker image and a5 code as I think GPL causes problems due to its viral nature.

**Comment by koadman** [comment]
ok, I've pushed a BSD license for the docker image.
A5-miseq is more complicated, as the dependencies it bundles each have their own licenses.

**Pull request merged**
